site_name: ModernStorage
site_url: https://google.github.com/modernstorage/
repo_name: google/modernstorage
repo_url: https://github.com/google/modernstorage
edit_uri: edit/main/docs/
site_description: "ModernStorage is a group of libraries that provide an abstraction layer over storage on Android to simplify its interactions"
site_author: Google
theme:
    name: material
    icon:
        logo: material/folder-outline
    favicon: images/favicon.png
    palette:
        primary: deep purple

nav:
    -   'Overview': README.md
    -   'MediaStore': mediastore.md
    -   'FileSystem': filesystem.md

# Extensions
markdown_extensions:
    - admonition
    -   codehilite:
            guess_lang: false
    - footnotes
    -   toc:
            permalink: true
    - pymdownx.betterem
    - pymdownx.superfences
    - pymdownx.tabbed
    -   pymdownx.tasklist:
            custom_checkbox: true

# Plugins
plugins:
    - search
    - macros

extra:
    lib_version: "1.0.0-alpha02"
