name: Build

on:
    push:
        branches:
            - main
        paths-ignore:
            - '**.md'
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 30

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Copy CI gradle.properties
                run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

            -   name: Set up JDK 11
                uses: actions/setup-java@v2
                with:
                    distribution: 'zulu'
                    java-version: 11
                    java-package: jdk

            -   name: Spotless checking
                run: ./gradlew spotlessCheck

            -   name: Build root project
                run: ./gradlew clean && ./gradlew build

            -   name: Run local tests
                run: ./gradlew testDebug --stacktrace

    test:
        needs: build
        runs-on: macOS-latest # enables hardware acceleration in the virtual machine
        timeout-minutes: 30
        strategy:
            matrix:
                api-level: [ 21, 23, 24, 26, 28, 29, 30, 31 ]

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Copy CI gradle.properties
                run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

            -   name: Set up JDK 11
                uses: actions/setup-java@v2
                with:
                    distribution: 'zulu'
                    java-version: 11
                    java-package: jdk

            -   name: Run instrumentation tests
                uses: reactivecircus/android-emulator-runner@v2
                with:
                    api-level: ${{ matrix.api-level }}
                    arch: x86
                    disable-animations: true
                    script: ./gradlew connectedCheck --stacktrace
